apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  annotations:
    source-file: my-podinfo-app-Kustomization-resource.yaml
  name: my-podinfo-app
  namespace: podinfo
spec:
  interval: 5m0s
  path: ./kustomize
  prune: false
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: podinfo
    namespace: podinfo
  targetNamespace: podinfo
  timeout: 3m0s
  wait: true
