apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  annotations:
    source-file: podinfo-app-Kustomization-resource.yaml
  name: podinfo-app
  namespace: apps
spec:
  interval: 5m0s
  path: ./kustomize
  prune: false
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: podinfo
    namespace: sources
  targetNamespace: apps
  timeout: 3m0s
  wait: true
