apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: podinfo
  namespace: podinfo
  annotations:
    source-file: "clusters/my-cluster/podinfo/podinfo-GitRepository-resource.yaml"
spec:
  interval: 2m0s
  ref: {}
  url: https://github.com/stefanprodan/podinfo
