apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  annotations:
    source-file: podinfo-HelmRepository-resource.yaml
  name: podinfo
  namespace: podinfo
spec:
  interval: 1m0s
  url: https://github.com/stefanprodan/podinfo
