apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  annotations:
    source-file: capacitor-Kustomization-resource.yaml
  name: capacitor
  namespace: capacitor
spec:
  interval: 5m0s
  path: ./
  prune: false
  retryInterval: 2m0s
  sourceRef:
    kind: OCIRepository
    name: capacitor
  targetNamespace: capacitor
  timeout: 3m0s
  wait: true
