apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  annotations:
    source-file: bitnami-GitRepository-resource.yaml
  name: bitnami
  namespace: nginx
spec:
  interval: 5m0s
  ref:
    branch: master
  url: https://charts.bitnami.com/bitnami
