apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  annotations:
    source-file: nginx-HelmRepository-resource.yaml
  name: nginx
  namespace: nginx
spec:
  interval: 5m0s
  url: https://charts.bitnami.com/bitnami
