apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    source-file: nginx-HelmRelease-resource.yaml
  name: nginx
  namespace: nginx
spec:
  install:
    remediation:
      retries: -1
  chart:
    spec:
      chart: nginx
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: nginx
      version: 15.x
  interval: 3m0s
  targetNamespace: nginx
  values:
    replicaCount: 2
