apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx
spec:
  chart:
    spec:
      chart: nginx
      sourceRef:
        kind: GitRepository
        name: bitnami
        namespace: nginx
      version: 15.x
  interval: 5m0s
  targetNamespace: nginx
  values:
    replicaCount: 2
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    service:
      type: ClusterIP
