apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    source-file: nginx1-HelmRelease-resource.yaml
  name: nginx1
  namespace: nginx
spec:
  chart:
    spec:
      chart: nginx
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: nginx
      version: 15.x
  interval: 5m0s
  targetNamespace: my-nginx-namespace
  values:
    replicaCount: 2
