apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    source-file: nginx-app-HelmRelease-resource.yaml
  name: nginx-app
  namespace: nginx
spec:
  chart:
    spec:
      chart: nginx
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: nginx
      version: 15.x
  interval: 5m0s
  targetNamespace: nginx
  values:
    replicaCount: 2
    service:
      type: ClusterIP
